In [1]:
import time
import numpy as np
import pandas as pd
from dateutil.parser import parse
from datetime import date, timedelta
from sklearn.preprocessing import LabelEncoder

In [2]:
data_path = '../rawdata/'

# 导入原始数据，预处理

In [3]:
air_reserve = pd.read_csv(data_path + 'air_reserve.csv').rename(columns={'air_store_id':'store_id'})
hpg_reserve = pd.read_csv(data_path + 'hpg_reserve.csv').rename(columns={'hpg_store_id':'store_id'})
air_store = pd.read_csv(data_path + 'air_store_info.csv').rename(columns={'air_store_id':'store_id'})
hpg_store = pd.read_csv(data_path + 'hpg_store_info.csv').rename(columns={'hpg_store_id':'store_id'})
air_visit = pd.read_csv(data_path + 'air_visit_data.csv').rename(columns={'air_store_id':'store_id'})
#以HPG的ID为索引
store_id_map = pd.read_csv(data_path + 'store_id_relation.csv').set_index('hpg_store_id',drop=False)
date_info = pd.read_csv(data_path + 'date_info.csv').rename(columns={'calendar_date': 'visit_date'}).drop('day_of_week',axis=1)
submission = pd.read_csv(data_path + 'sample_submission.csv')

In [6]:
#就餐日期，预定日期，周几
submission['visit_date'] = submission['id'].str[-10:]
submission['store_id'] = submission['id'].str[:-11]
air_reserve['visit_date'] = air_reserve['visit_datetime'].str[:10]
air_reserve['reserve_date'] = air_reserve['reserve_datetime'].str[:10]
air_reserve['dow'] = pd.to_datetime(air_reserve['visit_date']).dt.dayofweek
hpg_reserve['visit_date'] = hpg_reserve['visit_datetime'].str[:10]
hpg_reserve['reserve_date'] = hpg_reserve['reserve_datetime'].str[:10]
hpg_reserve['dow'] = pd.to_datetime(hpg_reserve['visit_date']).dt.dayofweek

In [7]:
#与submission保持一致，目的？
air_visit['id'] = air_visit['store_id'] + '_' + air_visit['visit_date']

In [8]:
#更新HPG餐厅ID
#store_id_map['air_store_id'] 为关联表中列名AIR ID，索引为HPG ID的Series。 通过map，将hpg_reserve的餐厅ID从HPG ID映射为AIR ID
#对于那些没有对应AIR ID 的餐厅，仍然使用HPG ID
hpg_reserve['store_id'] = hpg_reserve['store_id'].map(store_id_map['air_store_id']).fillna(hpg_reserve['store_id'])

In [9]:
#同上逻辑，彻底抹去HPG的概念
hpg_store['store_id'] = hpg_store['store_id'].map(store_id_map['air_store_id']).fillna(hpg_store['store_id'])
hpg_store.rename(columns={'hpg_genre_name':'air_genre_name','hpg_area_name':'air_area_name'},inplace=True)

In [10]:
#对训练集和测试集进行同样的处理，因此合并
data = pd.concat([air_visit, submission]).copy()

C:\Users\Alex\Anaconda3\envs\python36\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

In [11]:
data['dow'] = pd.to_datetime(data['visit_date']).dt.dayofweek

In [12]:
data.head()

,id,store_id,visit_date,visitors,dow
0,air_ba937bf13d40fb24_2016-01-13,air_ba937bf13d40fb24,2016-01-13,25,2
1,air_ba937bf13d40fb24_2016-01-14,air_ba937bf13d40fb24,2016-01-14,32,3
2,air_ba937bf13d40fb24_2016-01-15,air_ba937bf13d40fb24,2016-01-15,29,4
3,air_ba937bf13d40fb24_2016-01-16,air_ba937bf13d40fb24,2016-01-16,22,5
4,air_ba937bf13d40fb24_2016-01-18,air_ba937bf13d40fb24,2016-01-18,6,0

In [13]:
date_info.head()

   visit_date  holiday_flg
0  2016-01-01            1
1  2016-01-02            1
2  2016-01-03            1
3  2016-01-04            0
4  2016-01-05            0

In [14]:
#holiday_flg2 指代周末或者节假日
date_info['holiday_flg2'] = pd.to_datetime(date_info['visit_date']).dt.dayofweek
date_info['holiday_flg2'] = ((date_info['holiday_flg2']>4) | (date_info['holiday_flg']==1)).astype(int)

In [15]:
air_store['air_area_name0'] = air_store['air_area_name'].apply(lambda x: x.split(' ')[0])

In [16]:
#对餐厅类型和地理位置进行类型编码
lbl = LabelEncoder()
air_store['air_genre_name'] = lbl.fit_transform(air_store['air_genre_name'])
air_store['air_area_name0'] = lbl.fit_transform(air_store['air_area_name0'])

In [17]:
data.head()

,id,store_id,visit_date,visitors,dow
0,air_ba937bf13d40fb24_2016-01-13,air_ba937bf13d40fb24,2016-01-13,25,2
1,air_ba937bf13d40fb24_2016-01-14,air_ba937bf13d40fb24,2016-01-14,32,3
2,air_ba937bf13d40fb24_2016-01-15,air_ba937bf13d40fb24,2016-01-15,29,4
3,air_ba937bf13d40fb24_2016-01-16,air_ba937bf13d40fb24,2016-01-16,22,5
4,air_ba937bf13d40fb24_2016-01-18,air_ba937bf13d40fb24,2016-01-18,6,0

In [18]:
# log（1+x)处理顾客数
data['visitors'] = np.log1p(data['visitors'])

In [19]:
air_store.head()

,store_id,air_genre_name,air_area_name,latitude,longitude,air_area_name0
0,air_0f0cdeee6c9bf3d7,6,Hyōgo-ken Kōbe-shi Kumoidōri,34.695124,135.197852,3
1,air_7cc17a324ae5c7dc,6,Hyōgo-ken Kōbe-shi Kumoidōri,34.695124,135.197852,3
2,air_fee8dcf4d619598e,6,Hyōgo-ken Kōbe-shi Kumoidōri,34.695124,135.197852,3
3,air_a17f0778617c76e2,6,Hyōgo-ken Kōbe-shi Kumoidōri,34.695124,135.197852,3
4,air_83db5aff8f50478e,6,Tōkyō-to Minato-ku Shibakōen,35.658068,139.751599,7

In [20]:
#根据餐厅ID，将餐厅的详情融合到data中
data = data.merge(air_store,on='store_id',how='left')

In [21]:
data.head()

,id,store_id,visit_date,visitors,dow,air_genre_name,air_area_name,latitude,longitude,air_area_name0
0,air_ba937bf13d40fb24_2016-01-13,air_ba937bf13d40fb24,2016-01-13,3.258097,2,4,Tōkyō-to Minato-ku Shibakōen,35.658068,139.751599,7
1,air_ba937bf13d40fb24_2016-01-14,air_ba937bf13d40fb24,2016-01-14,3.496508,3,4,Tōkyō-to Minato-ku Shibakōen,35.658068,139.751599,7
2,air_ba937bf13d40fb24_2016-01-15,air_ba937bf13d40fb24,2016-01-15,3.401197,4,4,Tōkyō-to Minato-ku Shibakōen,35.658068,139.751599,7
3,air_ba937bf13d40fb24_2016-01-16,air_ba937bf13d40fb24,2016-01-16,3.135494,5,4,Tōkyō-to Minato-ku Shibakōen,35.658068,139.751599,7
4,air_ba937bf13d40fb24_2016-01-18,air_ba937bf13d40fb24,2016-01-18,1.945910,0,4,Tōkyō-to Minato-ku Shibakōen,35.658068,139.751599,7

In [22]:
#根据就餐日期，将日期的相关信息融合到data中
data = data.merge(date_info[['visit_date','holiday_flg','holiday_flg2']], on=['visit_date'],how='left')

In [23]:
data

,id,store_id,visit_date,visitors,dow,air_genre_name,air_area_name,latitude,longitude,air_area_name0,holiday_flg,holiday_flg2
0,air_ba937bf13d40fb24_2016-01-13,air_ba937bf13d40fb24,2016-01-13,3.258097,2,4,Tōkyō-to Minato-ku Shibakōen,35.658068,139.751599,7,0,0
1,air_ba937bf13d40fb24_2016-01-14,air_ba937bf13d40fb24,2016-01-14,3.496508,3,4,Tōkyō-to Minato-ku Shibakōen,35.658068,139.751599,7,0,0
2,air_ba937bf13d40fb24_2016-01-15,air_ba937bf13d40fb24,2016-01-15,3.401197,4,4,Tōkyō-to Minato-ku Shibakōen,35.658068,139.751599,7,0,0
3,air_ba937bf13d40fb24_2016-01-16,air_ba937bf13d40fb24,2016-01-16,3.135494,5,4,Tōkyō-to Minato-ku Shibakōen,35.658068,139.751599,7,0,1
4,air_ba937bf13d40fb24_2016-01-18,air_ba937bf13d40fb24,2016-01-18,1.945910,0,4,Tōkyō-to Minato-ku Shibakōen,35.658068,139.751599,7,0,0
5,air_ba937bf13d40fb24_2016-01-19,air_ba937bf13d40fb24,2016-01-19,2.302585,1,4,Tōkyō-to Minato-ku Shibakōen,35.658068,139.751599,7,0,0
6,air_ba937bf13d40fb24_2016-01-20,air_ba937bf13d40fb24,2016-01-20,3.465736,2,4,Tōkyō-to Minato-ku Shibakōen,35.658068,139.751599,7,0,0
7,air_ba937bf13d40fb24_2016-01-21,air_ba937bf13d40fb24,2016-01-21,3.091042,3,4,Tōkyō-to Minato-ku Shibakōen,35.658068,139.751599,7,0,0
8,air_ba937bf13d40fb24_2016-01-22,air_ba937bf13d40fb24,2016-01-22,2.944439,4,4,Tōkyō-to Minato-ku Shibakōen,35.658068,139.751599,7,0,0
9,air_ba937bf13d40fb24_2016-01-23,air_ba937bf13d40fb24,2016-01-23,3.295837,5,4,Tōkyō-to Minato-ku Shibakōen,35.658068,139.751599,7,0,1
10,air_ba937bf13d40fb24_2016-01-25,air_ba937bf13d40fb24,2016-01-25,3.091042,0,4,Tōkyō-to Minato-ku Shibakōen,35.658068,139.751599,7,0,0
11,air_ba937bf13d40fb24_2016-01-26,air_ba937bf13d40fb24,2016-01-26,2.484907,1,4,Tōkyō-to Minato-ku Shibakōen,35.658068,139.751599,7,0,0
12,air_ba937bf13d40fb24_2016-01-27,air_ba937bf13d40fb24,2016-01-27,3.218876,2,4,Tōkyō-to Minato-ku Shibakōen,35.658068,139.751599,7,0,0
13,air_ba937bf13d40fb24_2016-01-28,air_ba937bf13d40fb24,2016-01-28,3.091042,3,4,Tōkyō-to Minato-ku Shibakōen,35.658068,139.751599,7,0,0
14,air_ba937bf13d40fb24_2016-01-29,air_ba937bf13d40fb24,2016-01-29,3.295837,4,4,Tōkyō-to Minato-ku Shibakōen,35.658068,139.751599,7,0,0
15,air_ba937bf13d40fb24_2016-01-30,air_ba937bf13d40fb24,2016-01-30,1.945910,5,4,Tōkyō-to Minato-ku Shibakōen,35.658068,139.751599,7,0,1
16,air_ba937bf13d40fb24_2016-02-03,air_ba937bf13d40fb24,2016-02-03,2.944439,2,4,Tōkyō-to Minato-ku Shibakōen,35.658068,139.751599,7,0,0
17,air_ba937bf13d40fb24_2016-02-04,air_ba937bf13d40fb24,2016-02-04,2.564949,3,4,Tōkyō-to Minato-ku Shibakōen,35.658068,139.751599,7,0,0
18,air_ba937bf13d40fb24_2016-02-05,air_ba937bf13d40fb24,2016-02-05,3.828641,4,4,Tōkyō-to Minato-ku Shibakōen,35.658068,139.751599,7,0,0
19,air_ba937bf13d40fb24_2016-02-06,air_ba937bf13d40fb24,2016-02-06,2.772589,5,4,Tōkyō-to Minato-ku Shibakōen,35.658068,139.751599,7,0,1
20,air_ba937bf13d40fb24_2016-02-08,air_ba937bf13d40fb24,2016-02-08,2.995732,0,4,Tōkyō-to Minato-ku Shibakōen,35.658068,139.751599,7,0,0
21,air_ba937bf13d40fb24_2016-02-09,air_ba937bf13d40fb24,2016-02-09,2.772589,1,4,Tōkyō-to Minato-ku Shibakōen,35.658068,139.751599,7,0,0
22,air_ba937bf13d40fb24_2016-02-10,air_ba937bf13d40fb24,2016-02-10,3.496508,2,4,Tōkyō-to Minato-ku Shibakōen,35.658068,139.751599,7,0,0
23,air_ba937bf13d40fb24_2016-02-11,air_ba937bf13d40fb24,2016-02-11,1.386294,3,4,Tōkyō-to Minato-ku Shibakōen,35.658068,139.751599,7,1,1
24,air_ba937bf13d40fb24_2016-02-12,air_ba937bf13d40fb24,2016-02-12,3.295837,4,4,Tōkyō-to Minato-ku Shibakōen,35.658068,139.751599,7,0,0
25,air_ba937bf13d40fb24_2016-02-13,air_ba937bf13d40fb24,2016-02-13,2.197225,5,4,Tōkyō-to Minato-ku Shibakōen,35.658068,139.751599,7,0,1
26,air_ba937bf13d40fb24_2016-02-15,air_ba937bf13d40fb24,2016-02-15,2.708050,0,4,Tōkyō-to Minato-ku Shibakōen,35.658068,139.751599,7,0,0
27,air_ba937bf13d40fb24_2016-02-16,air_ba937bf13d40fb24,2016-02-16,2.772589,1,4,Tōkyō-to Minato-ku Shibakōen,35.658068,139.751599,7,0,0
28,air_ba937bf13d40fb24_2016-02-17,air_ba937bf13d40fb24,2016-02-17,2.890372,2,4,Tōkyō-to Minato-ku Shibakōen,35.658068,139.751599,7,0,0
29,air_ba937bf13d40fb24_2016-02-18,air_ba937bf13d40fb24,2016-02-18,3.135494,3,4,Tōkyō-to Minato-ku Shibakōen,35.658068,139.751599,7,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
284097,air_fff68b929994bfbd_2017-05-02,air_fff68b929994bfbd,2017-05-02,0.000000,1,1,Tōkyō-to Nakano-ku Nakano,35.708146,139.666288,7,0,0
284098,air_fff68b929994bfbd_2017-05-03,air_fff68b929994bfbd,2017-05-03,0.000000,2,1,Tōkyō-to Nakano-ku Nakano,35.708146,139.666288,7,1,1
284099,air_fff68b929994bfbd_2017-05-04,air_fff68b929994bfbd,2017-05-04,0.000000,3,1,Tōkyō-to Nakano-ku Nakano,35.708146,139.666288,7,1,1
284100,air_fff68b929994bfbd_2017-05-05,air_fff68b929994bfbd,2017-05-05,0.000000,4,1,Tōkyō-to Nakano-ku Nakano,35.708146,139.666288,7,1,1
284101,air_fff68b929994bfbd_2017-05-06,air_fff68b929994bfbd,2017-05-06,0.000000,5,1,Tōkyō-to Nakano-ku Nakano,35.708146,139.666288,7,0,1
284102,air_fff68b929994bfbd_2017-05-07,air_fff68b929994bfbd,2017-05-07,0.000000,6,1,Tōkyō-to Nakano-ku Nakano,35.708146,139.666288,7,0,1
284103,air_fff68b929994bfbd_2017-05-08,air_fff68b929994bfbd,2017-05-08,0.000000,0,1,Tōkyō-to Nakano-ku Nakano,35.708146,139.666288,7,0,0
284104,air_fff68b929994bfbd_2017-05-09,air_fff68b929994bfbd,2017-05-09,0.000000,1,1,Tōkyō-to Nakano-ku Nakano,35.708146,139.666288,7,0,0
284105,air_fff68b929994bfbd_2017-05-10,air_fff68b929994bfbd,2017-05-10,0.000000,2,1,Tōkyō-to Nakano-ku Nakano,35.708146,139.666288,7,0,0
284106,air_fff68b929994bfbd_2017-05-11,air_fff68b929994bfbd,2017-05-11,0.000000,3,1,Tōkyō-to Nakano-ku Nakano,35.708146,139.666288,7,0,0
284107,air_fff68b929994bfbd_2017-05-12,air_fff68b929994bfbd,2017-05-12,0.000000,4,1,Tōkyō-to Nakano-ku Nakano,35.708146,139.666288,7,0,0
284108,air_fff68b929994bfbd_2017-05-13,air_fff68b929994bfbd,2017-05-13,0.000000,5,1,Tōkyō-to Nakano-ku Nakano,35.708146,139.666288,7,0,1
284109,air_fff68b929994bfbd_2017-05-14,air_fff68b929994bfbd,2017-05-14,0.000000,6,1,Tōkyō-to Nakano-ku Nakano,35.708146,139.666288,7,0,1
284110,air_fff68b929994bfbd_2017-05-15,air_fff68b929994bfbd,2017-05-15,0.000000,0,1,Tōkyō-to Nakano-ku Nakano,35.708146,139.666288,7,0,0
284111,air_fff68b929994bfbd_2017-05-16,air_fff68b929994bfbd,2017-05-16,0.000000,1,1,Tōkyō-to Nakano-ku Nakano,35.708146,139.666288,7,0,0
284112,air_fff68b929994bfbd_2017-05-17,air_fff68b929994bfbd,2017-05-17,0.000000,2,1,Tōkyō-to Nakano-ku Nakano,35.708146,139.666288,7,0,0
284113,air_fff68b929994bfbd_2017-05-18,air_fff68b929994bfbd,2017-05-18,0.000000,3,1,Tōkyō-to Nakano-ku Nakano,35.708146,139.666288,7,0,0
284114,air_fff68b929994bfbd_2017-05-19,air_fff68b929994bfbd,2017-05-19,0.000000,4,1,Tōkyō-to Nakano-ku Nakano,35.708146,139.666288,7,0,0
284115,air_fff68b929994bfbd_2017-05-20,air_fff68b929994bfbd,2017-05-20,0.000000,5,1,Tōkyō-to Nakano-ku Nakano,35.708146,139.666288,7,0,1
284116,air_fff68b929994bfbd_2017-05-21,air_fff68b929994bfbd,2017-05-21,0.000000,6,1,Tōkyō-to Nakano-ku Nakano,35.708146,139.666288,7,0,1
284117,air_fff68b929994bfbd_2017-05-22,air_fff68b929994bfbd,2017-05-22,0.000000,0,1,Tōkyō-to Nakano-ku Nakano,35.708146,139.666288,7,0,0
284118,air_fff68b929994bfbd_2017-05-23,air_fff68b929994bfbd,2017-05-23,0.000000,1,1,Tōkyō-to Nakano-ku Nakano,35.708146,139.666288,7,0,0
284119,air_fff68b929994bfbd_2017-05-24,air_fff68b929994bfbd,2017-05-24,0.000000,2,1,Tōkyō-to Nakano-ku Nakano,35.708146,139.666288,7,0,0
284120,air_fff68b929994bfbd_2017-05-25,air_fff68b929994bfbd,2017-05-25,0.000000,3,1,Tōkyō-to Nakano-ku Nakano,35.708146,139.666288,7,0,0
284121,air_fff68b929994bfbd_2017-05-26,air_fff68b929994bfbd,2017-05-26,0.000000,4,1,Tōkyō-to Nakano-ku Nakano,35.708146,139.666288,7,0,0
284122,air_fff68b929994bfbd_2017-05-27,air_fff68b929994bfbd,2017-05-27,0.000000,5,1,Tōkyō-to Nakano-ku Nakano,35.708146,139.666288,7,0,1
284123,air_fff68b929994bfbd_2017-05-28,air_fff68b929994bfbd,2017-05-28,0.000000,6,1,Tōkyō-to Nakano-ku Nakano,35.708146,139.666288,7,0,1
284124,air_fff68b929994bfbd_2017-05-29,air_fff68b929994bfbd,2017-05-29,0.000000,0,1,Tōkyō-to Nakano-ku Nakano,35.708146,139.666288,7,0,0
284125,air_fff68b929994bfbd_2017-05-30,air_fff68b929994bfbd,2017-05-30,0.000000,1,1,Tōkyō-to Nakano-ku Nakano,35.708146,139.666288,7,0,0
284126,air_fff68b929994bfbd_2017-05-31,air_fff68b929994bfbd,2017-05-31,0.000000,2,1,Tōkyō-to Nakano-ku Nakano,35.708146,139.666288,7,0,0

# 工具函数

In [24]:
#合并集合
#集合中后置位的对象将覆盖前置位的对象在result中保存的内容
def concat(L):
    result = None
    for l in L:
        if result is None:
            result = l
        else:
            try:
                result[l.columns.tolist()] = l
            except:
                print(l.head())
    return result

In [25]:

def left_merge(data1,data2,on):
    if type(on) != list:
        on = [on]
    if (set(on) & set(data2.columns)) != set(on):
        data2_temp = data2.reset_index()
    else:
        data2_temp = data2.copy()
    columns = [f for f in data2.columns if f not in on]
    result = data1.merge(data2_temp,on=on,how='left')
    result = result[columns]
    return result

In [26]:
#输入起始日期以及天数增量，返回结束日期
def date_add_days(start_date, days):
    end_date = parse(start_date[:10]) + timedelta(days=days)
    end_date = end_date.strftime('%Y-%m-%d')
    return end_date

In [27]:
def make_feats(end_date,n_day):
    t0 = time.time()
    key = end_date,n_day
    print('data key为：{}'.format(key))
    print('add label')
    # 在周期内的日期上做各种特征
    label = get_label(end_date,n_day)

    print('make feature...')
    result = [label]
    # 增加历史1000、56、28、14天内的就餐人数stats作为特征
    result.append(get_store_visitor_feat(label, key, 1000))        # store features
    result.append(get_store_visitor_feat(label, key, 56))          # store features
    result.append(get_store_visitor_feat(label, key, 28))          # store features
    result.append(get_store_visitor_feat(label, key, 14))          # store features
    # 增加历史1000天内的加权就餐人数，0.985^（天数差异）
    result.append(get_store_exp_visitor_feat(label, key, 1000))    # store exp features
    # 增加历史1000、56、28、14天内的，按周几划分的就餐人数stats作为特征
    result.append(get_store_week_feat(label, key, 1000))           # store dow features
    result.append(get_store_week_feat(label, key, 56))             # store dow features
    result.append(get_store_week_feat(label, key, 28))             # store dow features
    result.append(get_store_week_feat(label, key, 14))             # store dow features
    # ？？？？？？？？？？？？？
    result.append(get_store_week_diff_feat(label, key, 58))       # store dow diff features
    result.append(get_store_week_diff_feat(label, key, 1000))      # store dow diff features
    # 增加历史1000天内的，按周几划分的就餐人数stats作为特征
    result.append(get_store_all_week_feat(label, key, 1000))       # store all week feat
    # 增加历史1000天内的，按周几划分的加权就餐人数stats作为特征
    result.append(get_store_week_exp_feat(label, key, 1000))       # store dow exp feat
    # 增加历史1000天内的，按是否为假日划分的就餐人数stats作为特征
    result.append(get_store_holiday_feat(label, key, 1000))        # store holiday feat
    # 增加历史1000、56、28天内的，按餐厅类型划分的就餐人数stats作为特征
    result.append(get_genre_visitor_feat(label, key, 1000))         # genre feature
    result.append(get_genre_visitor_feat(label, key, 56))           # genre feature
    result.append(get_genre_visitor_feat(label, key, 28))           # genre feature
    # 增加历史1000天内的，按餐厅类型划分的加权就餐人数stats作为特征
    result.append(get_genre_exp_visitor_feat(label, key, 1000))     # genre feature
    # 增加历史1000、56、28天内的，按餐厅类型以及周几划分的就餐人数stats作为特征
    result.append(get_genre_week_feat(label, key, 1000))            # genre dow feature
    result.append(get_genre_week_feat(label, key, 56))              # genre dow feature
    result.append(get_genre_week_feat(label, key, 28))              # genre dow feature
    # 增加历史1000天内的，按餐厅类型以及周几划分的加权就餐人数stats作为特征
    result.append(get_genre_week_exp_feat(label, key, 1000))        # genre dow exp feature
    # ？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？
    result.append(get_reserve_feat(label,key))                      # air_reserve
    # ？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？
    result.append(get_first_last_time(label,key,1000))             # first time and last time

    result.append(label)

    print('merge...')
    result = concat(result)

    result = second_feat(result)

    print('data shape：{}'.format(result.shape))
    print('spending {}s'.format(time.time() - t0))
    return result

In [28]:
# 输入周期起始日期以及周期天数，返回在此周期内数据（包括周期起始日期》，《就餐日期与周期起始日期的差异》，《就餐月份》
# 《就餐年份》，《3天前是否为假日1》、《3天前是否为假日2》。。。《1天后是否为假日1》、《1天后是否为假日2》等特征
def get_label(end_date,n_day):
    label_end_date = date_add_days(end_date, n_day)
    # 就餐日期在[开始日期，开始日期+区间天数)范围内的数据
    label = data[(data['visit_date'] < label_end_date) & (data['visit_date'] >= end_date)].copy()
    # 数据中增加《周期起始日期》列
    label['end_date'] = end_date
    # 数据中增加就餐日期与开始日期之间天数的差异《就餐日期与周期起始日期的差异》
    label['diff_of_day'] = label['visit_date'].apply(lambda x: diff_of_days(x,end_date))
    # 数据中增加《就餐月份》
    label['month'] = label['visit_date'].str[5:7].astype(int)
    # 数据中增加《就餐年份》
    label['year'] = label['visit_date'].str[:4].astype(int)
    # 以i=3为例，在数据中增加《3天前是否为假日1》、《3天前是否为假日2》列
    for i in [3,2,1,-1]:
        date_info_temp = date_info.copy()
        date_info_temp['visit_date'] = date_info_temp['visit_date'].apply(lambda x: date_add_days(x,i))
        date_info_temp.rename(columns={'holiday_flg':'ahead_holiday_{}'.format(i),'holiday_flg2':'ahead_holiday2_{}'.format(i)},inplace=True)
        label = label.merge(date_info_temp, on=['visit_date'],how='left')
    label = label.reset_index(drop=True)
    return label

In [30]:
# 计算前一个日期减去后一个日期的天数
def diff_of_days(day1, day2):
    days = (parse(day1[:10]) - parse(day2[:10])).days
    return days

In [31]:
# 输入日期到输入日期之前n_day的时间范围内就餐人数的stats
def get_store_visitor_feat(label, key, n_day):
    # 就餐人数特征提取的起始日期为周期起始日期的n_day前
    start_date = date_add_days(key[0],-n_day)
    data_temp = data[(data.visit_date < key[0]) & (data.visit_date > start_date)].copy()
    # 该日期范围内每个餐厅就餐人数的stats
    result = data_temp.groupby(['store_id'], as_index=False)['visitors'].agg({'store_min{}'.format(n_day): 'min',
                                                                             'store_mean{}'.format(n_day): 'mean',
                                                                             'store_median{}'.format(n_day): 'median',
                                                                             'store_max{}'.format(n_day): 'max',
                                                                             'store_count{}'.format(n_day): 'count',
                                                                             'store_std{}'.format(n_day): 'std',
                                                                             'store_skew{}'.format(n_day): 'skew'})
    result = left_merge(label, result, on=['store_id']).fillna(0)
    return result

In [32]:
# 就餐人数增加权重，0.985^(天数差异)
def get_store_exp_visitor_feat(label, key, n_day):
    start_date = date_add_days(key[0], -n_day)
    data_temp = data[(data.visit_date < key[0]) & (data.visit_date > start_date)].copy()
    data_temp['visit_date'] = data_temp['visit_date'].apply(lambda x: diff_of_days(key[0],x))
    # 日期权重为0.985^(天数差异)
    data_temp['weight'] = data_temp['visit_date'].apply(lambda x: 0.985**x)
    data_temp['visitors'] = data_temp['visitors'] * data_temp['weight']
    result1 = data_temp.groupby(['store_id'], as_index=False)['visitors'].agg({'store_exp_mean{}'.format(n_day): 'sum'})
    result2 = data_temp.groupby(['store_id'], as_index=False)['weight'].agg({'store_exp_weight_sum{}'.format(n_day): 'sum'})
    result = result1.merge(result2, on=['store_id'], how='left')
    result['store_exp_mean{}'.format(n_day)] = result['store_exp_mean{}'.format(n_day)]/result['store_exp_weight_sum{}'.format(n_day)]
    result = left_merge(label, result, on=['store_id']).fillna(0)
    return result

In [33]:
# 按周几划分的就餐人数stats
def get_store_week_feat(label, key, n_day):
    start_date = date_add_days(key[0], -n_day)
    data_temp = data[(data.visit_date < key[0]) & (data.visit_date > start_date)].copy()
    result = data_temp.groupby(['store_id', 'dow'], as_index=False)['visitors'].agg({'store_dow_min{}'.format(n_day): 'min',
                                                                                     'store_dow_mean{}'.format(n_day): 'mean',
                                                                                     'store_dow_median{}'.format(n_day): 'median',
                                                                                     'store_dow_max{}'.format(n_day): 'max',
                                                                                     'store_dow_count{}'.format(n_day): 'count',
                                                                                     'store_dow_std{}'.format(n_day): 'std',
                                                                                     'store_dow_skew{}'.format(n_day): 'skew'})
    result = left_merge(label, result, on=['store_id', 'dow']).fillna(0)
    return result

In [34]:
# 需要继续研究！！！！！！！！！！！！！！！！！！！！！！！！！！
def get_store_week_diff_feat(label, key, n_day):
    start_date = date_add_days(key[0], -n_day)
    data_temp = data[(data.visit_date < key[0]) & (data.visit_date > start_date)].copy()
    result = data_temp.set_index(['store_id','visit_date'])['visitors'].unstack()
    result = result.diff(axis=1).iloc[:,1:]
    c = result.columns
    result['store_diff_mean'] = np.abs(result[c]).mean(axis=1)
    result['store_diff_std'] = result[c].std(axis=1)
    result['store_diff_max'] = result[c].max(axis=1)
    result['store_diff_min'] = result[c].min(axis=1)
    result = left_merge(label, result[['store_diff_mean', 'store_diff_std', 'store_diff_max', 'store_diff_min']],on=['store_id']).fillna(0)
    return result

In [35]:
# 与get_store_week_feat有何区别？
def get_store_all_week_feat(label, key, n_day):
    start_date = date_add_days(key[0], -n_day)
    data_temp = data[(data.visit_date < key[0]) & (data.visit_date > start_date)].copy()
    result_temp = data_temp.groupby(['store_id', 'dow'],as_index=False)['visitors'].agg({'store_dow_mean{}'.format(n_day): 'mean',
                                                                     'store_dow_median{}'.format(n_day): 'median',
                                                                     'store_dow_sum{}'.format(n_day): 'max',
                                                                     'store_dow_count{}'.format(n_day): 'count'})
    result = pd.DataFrame()
    for i in range(7):
        result_sub = result_temp[result_temp['dow']==i].copy()
        result_sub = result_sub.set_index('store_id')
        result_sub = result_sub.add_prefix(str(i))
        result_sub = left_merge(label, result_sub, on=['store_id']).fillna(0)
        result = pd.concat([result,result_sub],axis=1)
    return result

In [36]:
# 与周期起始日期天数差异的指数权重
def get_store_week_exp_feat(label, key, n_day):
    start_date = date_add_days(key[0], -n_day)
    data_temp = data[(data.visit_date < key[0]) & (data.visit_date > start_date)].copy()
    data_temp['visit_date'] = data_temp['visit_date'].apply(lambda x: diff_of_days(key[0],x))
    data_temp['visitors2'] = data_temp['visitors']
    result = None
    for i in [0.9,0.95,0.97,0.98,0.985,0.99,0.999,0.9999]:
        data_temp['weight'] = data_temp['visit_date'].apply(lambda x: i**x)
        data_temp['visitors1'] = data_temp['visitors'] * data_temp['weight']
        data_temp['visitors2'] = data_temp['visitors2'] * data_temp['weight']
        result1 = data_temp.groupby(['store_id', 'dow'], as_index=False)['visitors1'].agg({'store_dow_exp_mean{}_{}'.format(n_day,i): 'sum'})
        result3 = data_temp.groupby(['store_id', 'dow'], as_index=False)['visitors2'].agg({'store_dow_exp_mean2{}_{}'.format(n_day, i): 'sum'})
        result2 = data_temp.groupby(['store_id', 'dow'], as_index=False)['weight'].agg({'store_dow_exp_weight_sum{}_{}'.format(n_day,i): 'sum'})
        result_temp = result1.merge(result2, on=['store_id', 'dow'], how='left')
        result_temp = result_temp.merge(result3, on=['store_id', 'dow'], how='left')
        result_temp['store_dow_exp_mean{}_{}'.format(n_day,i)] = result_temp['store_dow_exp_mean{}_{}'.format(n_day,i)]/result_temp['store_dow_exp_weight_sum{}_{}'.format(n_day,i)]
        result_temp['store_dow_exp_mean2{}_{}'.format(n_day, i)] = result_temp[ 'store_dow_exp_mean2{}_{}'.format(n_day, i)]/result_temp['store_dow_exp_weight_sum{}_{}'.format(n_day, i)]
        if result is None:
            result = result_temp
        else:
            result = result.merge(result_temp,on=['store_id','dow'],how='left')
    result = left_merge(label, result, on=['store_id', 'dow']).fillna(0)
    return result

In [37]:
def get_store_holiday_feat(label, key, n_day):
    start_date = date_add_days(key[0], -n_day)
    data_temp = data[(data.visit_date < key[0]) & (data.visit_date > start_date)].copy()
    result1 = data_temp.groupby(['store_id', 'holiday_flg'], as_index=False)['visitors'].agg(
        {'store_holiday_min{}'.format(n_day): 'min',
         'store_holiday_mean{}'.format(n_day): 'mean',
         'store_holiday_median{}'.format(n_day): 'median',
         'store_holiday_max{}'.format(n_day): 'max',
         'store_holiday_count{}'.format(n_day): 'count',
         'store_holiday_std{}'.format(n_day): 'std',
         'store_holiday_skew{}'.format(n_day): 'skew'})
    result1 = left_merge(label, result1, on=['store_id', 'holiday_flg']).fillna(0)
    result2 = data_temp.groupby(['store_id', 'holiday_flg2'], as_index=False)['visitors'].agg(
        {'store_holiday2_min{}'.format(n_day): 'min',
         'store_holiday2_mean{}'.format(n_day): 'mean',
         'store_holiday2_median{}'.format(n_day): 'median',
         'store_holiday2_max{}'.format(n_day): 'max',
         'store_holiday2_count{}'.format(n_day): 'count',
         'store_holiday2_std{}'.format(n_day): 'std',
         'store_holiday2_skew{}'.format(n_day): 'skew'})
    result2 = left_merge(label, result2, on=['store_id', 'holiday_flg2']).fillna(0)
    result = pd.concat([result1, result2], axis=1)
    return result

In [38]:
def get_genre_visitor_feat(label, key, n_day):
    start_date = date_add_days(key[0],-n_day)
    data_temp = data[(data.visit_date < key[0]) & (data.visit_date > start_date)].copy()
    result = data_temp.groupby(['air_genre_name'], as_index=False)['visitors'].agg({'genre_min{}'.format(n_day): 'min',
                                                                             'genre_mean{}'.format(n_day): 'mean',
                                                                             'genre_median{}'.format(n_day): 'median',
                                                                             'genre_max{}'.format(n_day): 'max',
                                                                             'genre_count{}'.format(n_day): 'count',
                                                                             'genre_std{}'.format(n_day): 'std',
                                                                             'genre_skew{}'.format(n_day): 'skew'})
    result = left_merge(label, result, on=['air_genre_name']).fillna(0)
    return result

In [39]:
def get_genre_exp_visitor_feat(label, key, n_day):
    start_date = date_add_days(key[0], -n_day)
    data_temp = data[(data.visit_date < key[0]) & (data.visit_date > start_date)].copy()
    data_temp['visit_date'] = data_temp['visit_date'].apply(lambda x: diff_of_days(key[0],x))
    data_temp['weight'] = data_temp['visit_date'].apply(lambda x: 0.985**x)
    data_temp['visitors'] = data_temp['visitors'] * data_temp['weight']
    result1 = data_temp.groupby(['air_genre_name'], as_index=False)['visitors'].agg({'genre_exp_mean{}'.format(n_day): 'sum'})
    result2 = data_temp.groupby(['air_genre_name'], as_index=False)['weight'].agg({'genre_exp_weight_sum{}'.format(n_day): 'sum'})
    result = result1.merge(result2, on=['air_genre_name'], how='left')
    result['genre_exp_mean{}'.format(n_day)] = result['genre_exp_mean{}'.format(n_day)]/result['genre_exp_weight_sum{}'.format(n_day)]
    result = left_merge(label, result, on=['air_genre_name']).fillna(0)
    return result

In [40]:
def get_genre_week_feat(label, key, n_day):
    start_date = date_add_days(key[0], -n_day)
    data_temp = data[(data.visit_date < key[0]) & (data.visit_date > start_date)].copy()
    result = data_temp.groupby(['air_genre_name', 'dow'], as_index=False)['visitors'].agg({'genre_dow_min{}'.format(n_day): 'min',
                                                                                         'genre_dow_mean{}'.format(n_day): 'mean',
                                                                                         'genre_dow_median{}'.format(n_day): 'median',
                                                                                         'genre_dow_max{}'.format(n_day): 'max',
                                                                                         'genre_dow_count{}'.format(n_day): 'count',
                                                                                         'genre_dow_std{}'.format(n_day): 'std',
                                                                                         'genre_dow_skew{}'.format(n_day): 'skew'})
    result = left_merge(label, result, on=['air_genre_name', 'dow']).fillna(0)
    return result

In [41]:
def get_genre_week_exp_feat(label, key, n_day):
    start_date = date_add_days(key[0], -n_day)
    data_temp = data[(data.visit_date < key[0]) & (data.visit_date > start_date)].copy()
    data_temp['visit_date'] = data_temp['visit_date'].apply(lambda x: diff_of_days(key[0],x))
    data_temp['weight'] = data_temp['visit_date'].apply(lambda x: 0.985**x)
    data_temp['visitors'] = data_temp['visitors'] * data_temp['weight']
    result1 = data_temp.groupby(['air_genre_name', 'dow'], as_index=False)['visitors'].agg({'genre_dow_exp_mean{}'.format(n_day): 'sum'})
    result2 = data_temp.groupby(['air_genre_name', 'dow'], as_index=False)['weight'].agg({'genre_dow_exp_weight_sum{}'.format(n_day): 'sum'})
    result = result1.merge(result2, on=['air_genre_name', 'dow'], how='left')
    result['genre_dow_exp_mean{}'.format(n_day)] = result['genre_dow_exp_mean{}'.format(n_day)]/result['genre_dow_exp_weight_sum{}'.format(n_day)]
    result = left_merge(label, result, on=['air_genre_name', 'dow']).fillna(0)
    return result

In [42]:
# air_reserve  
def get_reserve_feat(label,key):
    label_end_date = date_add_days(key[0], key[1])
    # 预约就餐日期在日期窗内，且预约日期在日期窗起始日期前
    air_reserve_temp = air_reserve[(air_reserve.visit_date >= key[0]) &             # key[0] 是'2017-04-23'
                                   (air_reserve.visit_date < label_end_date) &      # label_end_date 是'2017-05-31'
                                   (air_reserve.reserve_date < key[0])].copy()
    # 补充餐厅详情
    air_reserve_temp = air_reserve_temp.merge(air_store,on='store_id',how='left')
    # 增加《预约就餐日期-预约日期》列
    air_reserve_temp['diff_time'] = (pd.to_datetime(air_reserve['visit_datetime'])-pd.to_datetime(air_reserve['reserve_datetime'])).dt.days
    air_reserve_temp = air_reserve_temp.merge(air_store,on='store_id')
    # 根据餐厅ID和就餐日期划分，统计《预约就餐人数总和》和《预约就餐次数》
    air_result = air_reserve_temp.groupby(['store_id', 'visit_date'])['reserve_visitors'].agg(
        {'air_reserve_visitors': 'sum',
         'air_reserve_count': 'count'})
    # 根据餐厅ID和就餐日期划分，统计《预约就餐日期-预约日期平均值》
    air_store_diff_time_mean = air_reserve_temp.groupby(['store_id', 'visit_date'])['diff_time'].agg(
        {'air_store_diff_time_mean': 'mean'})
    # 根据就餐日期划分，统计《所有餐厅预约就餐日期-预约日期平均值》
    air_diff_time_mean = air_reserve_temp.groupby(['visit_date'])['diff_time'].agg(
        {'air_diff_time_mean': 'mean'})
    # 根据餐厅ID和就餐日期划分，且所以餐厅ID的所有就餐日期都存在。实际不存在的NaN用0替代
    air_result = air_result.unstack().fillna(0).stack()
    air_date_result = air_reserve_temp.groupby(['visit_date'])['reserve_visitors'].agg({
        'air_date_visitors': 'sum',
        'air_date_count': 'count'})
    # 同样逻辑处理HPG系统
    hpg_reserve_temp = hpg_reserve[(hpg_reserve.visit_date >= key[0]) & (hpg_reserve.visit_date < label_end_date) & (hpg_reserve.reserve_date < key[0])].copy()
    hpg_reserve_temp['diff_time'] = (pd.to_datetime(hpg_reserve['visit_datetime']) - pd.to_datetime(hpg_reserve['reserve_datetime'])).dt.days
    hpg_result = hpg_reserve_temp.groupby(['store_id', 'visit_date'])['reserve_visitors'].agg({'hpg_reserve_visitors': 'sum',
                                                                                               'hpg_reserve_count': 'count'})
    hpg_result = hpg_result.unstack().fillna(0).stack()
    hpg_date_result = hpg_reserve_temp.groupby(['visit_date'])['reserve_visitors'].agg({
        'hpg_date_visitors': 'sum',
        'hpg_date_count': 'count'})
    hpg_store_diff_time_mean = hpg_reserve_temp.groupby(['store_id', 'visit_date'])['diff_time'].agg(
        {'hpg_store_diff_time_mean': 'mean'})
    hpg_diff_time_mean = hpg_reserve_temp.groupby(['visit_date'])['diff_time'].agg(
        {'hpg_diff_time_mean': 'mean'})
    air_result = left_merge(label, air_result, on=['store_id','visit_date']).fillna(0)
    air_store_diff_time_mean = left_merge(label, air_store_diff_time_mean, on=['store_id', 'visit_date']).fillna(0)
    hpg_result = left_merge(label, hpg_result, on=['store_id', 'visit_date']).fillna(0)
    hpg_store_diff_time_mean = left_merge(label, hpg_store_diff_time_mean, on=['store_id', 'visit_date']).fillna(0)
    air_date_result = left_merge(label, air_date_result, on=['visit_date']).fillna(0)
    air_diff_time_mean = left_merge(label, air_diff_time_mean, on=['visit_date']).fillna(0)
    hpg_date_result = left_merge(label, hpg_date_result, on=['visit_date']).fillna(0)
    hpg_diff_time_mean = left_merge(label, hpg_diff_time_mean, on=['visit_date']).fillna(0)
    result = pd.concat([air_result,hpg_result,air_date_result,hpg_date_result,air_store_diff_time_mean,
                        hpg_store_diff_time_mean,air_diff_time_mean,hpg_diff_time_mean],axis=1)
    return result

In [43]:
# ？？？？？？？？？？？？？？？？？？？
def get_first_last_time(label, key, n_day):
    start_date = date_add_days(key[0], -n_day)
    data_temp = data[(data.visit_date < key[0]) & (data.visit_date > start_date)].copy()
    data_temp = data_temp.sort_values('visit_date')
    result = data_temp.groupby('store_id')['visit_date'].agg({'first_time':lambda x: diff_of_days(key[0],np.min(x)),
                                                              'last_time':lambda x: diff_of_days(key[0],np.max(x)),})
    result = left_merge(label, result, on=['store_id']).fillna(0)
    return result

In [44]:
# second feature
def second_feat(result):
    result['store_mean_14_28_rate'] = result['store_mean14']/(result['store_mean28']+0.01)
    result['store_mean_28_56_rate'] = result['store_mean28'] / (result['store_mean56'] + 0.01)
    result['store_mean_56_1000_rate'] = result['store_mean56'] / (result['store_mean1000'] + 0.01)
    result['genre_mean_28_56_rate'] = result['genre_mean28'] / (result['genre_mean56'] + 0.01)
    result['sgenre_mean_56_1000_rate'] = result['genre_mean56'] / (result['genre_mean1000'] + 0.01)
    return result

# 开始训练

In [45]:
import datetime
import lightgbm as lgb

In [46]:
train_feat = pd.DataFrame()
start_date = '2017-03-12'

In [47]:
for i in range(58):
    train_feat_sub = make_feats(date_add_days(start_date, i*(-7)),39)
    train_feat = pd.concat([train_feat,train_feat_sub])
    
    
for i in range(1,6):
    train_feat_sub = make_feats(date_add_days(start_date,i*(7)),42-(i*7))
    train_feat = pd.concat([train_feat,train_feat_sub])
test_feat = make_feats(date_add_days(start_date, 42),39)

data key为：('2017-03-12', 39)
add label
make feature...

C:\Users\Alex\Anaconda3\envs\python36\lib\site-packages\ipykernel_launcher.py:12: FutureWarning: using a dict on a Series for aggregation
is deprecated and will be removed in a future version
  if sys.path[0] == '':
C:\Users\Alex\Anaconda3\envs\python36\lib\site-packages\ipykernel_launcher.py:14: FutureWarning: using a dict on a Series for aggregation
is deprecated and will be removed in a future version

C:\Users\Alex\Anaconda3\envs\python36\lib\site-packages\ipykernel_launcher.py:16: FutureWarning: using a dict on a Series for aggregation
is deprecated and will be removed in a future version
  app.launch_new_instance()
C:\Users\Alex\Anaconda3\envs\python36\lib\site-packages\ipykernel_launcher.py:20: FutureWarning: using a dict on a Series for aggregation
is deprecated and will be removed in a future version
C:\Users\Alex\Anaconda3\envs\python36\lib\site-packages\ipykernel_launcher.py:24: FutureWarning: using a dict on a Series for aggregation
is deprecated and will be removed in a future version
C:\Users\Alex\Anaconda3\envs\python36\lib\site-packages\ipykernel_launcher.py:28: FutureWarning: using a dict on a Series for aggregation
is deprecated and will be removed in a future version
C:\Users\Alex\Anaconda3\envs\python36\lib\site-packages\ipykernel_launcher.py:30: FutureWarning: using a dict on a Series for aggregation
is deprecated and will be removed in a future version
C:\Users\Alex\Anaconda3\envs\python36\lib\site-packages\ipykernel_launcher.py:32: FutureWarning: using a dict on a Series for aggregation
is deprecated and will be removed in a future version
C:\Users\Alex\Anaconda3\envs\python36\lib\site-packages\ipykernel_launcher.py:7: FutureWarning: using a dict on a Series for aggregation
is deprecated and will be removed in a future version
  import sys

merge...
data shape：(27728, 224)
spending 98.3319959640503s
data key为：('2017-03-05', 39)
add label
make feature...
merge...
data shape：(27705, 224)
spending 94.70865845680237s
data key为：('2017-02-26', 39)
add label
make feature...
merge...
data shape：(27745, 224)
spending 93.11991763114929s
data key为：('2017-02-19', 39)
add label
make feature...
merge...
data shape：(27696, 224)
spending 90.9906108379364s
data key为：('2017-02-12', 39)
add label
make feature...
merge...
data shape：(27596, 224)
spending 89.07774639129639s
data key为：('2017-02-05', 39)
add label
make feature...
merge...
data shape：(27561, 224)
spending 86.86759924888611s
data key为：('2017-01-29', 39)
add label
make feature...
merge...
data shape：(27511, 224)
spending 85.06345915794373s
data key为：('2017-01-22', 39)
add label
make feature...
merge...
data shape：(27474, 224)
spending 83.14163827896118s
data key为：('2017-01-15', 39)
add label
make feature...
merge...
data shape：(27389, 224)
spending 81.44318294525146s
data key为：('2017-01-08', 39)
add label
make feature...
merge...
data shape：(27201, 224)
spending 79.46746778488159s
data key为：('2017-01-01', 39)
add label
make feature...
merge...
data shape：(25360, 224)
spending 77.92459321022034s
data key为：('2016-12-25', 39)
add label
make feature...
merge...
data shape：(24721, 224)
spending 76.04362297058105s
data key为：('2016-12-18', 39)
add label
make feature...
merge...
data shape：(24712, 224)
spending 75.12005233764648s
data key为：('2016-12-11', 39)
add label
make feature...
merge...
data shape：(24761, 224)
spending 72.59780168533325s
data key为：('2016-12-04', 39)
add label
make feature...
merge...
data shape：(24817, 224)
spending 70.91231036186218s
data key为：('2016-11-27', 39)
add label
make feature...
merge...
data shape：(25184, 224)
spending 68.81296730041504s
data key为：('2016-11-20', 39)
add label
make feature...
merge...
data shape：(27458, 224)
spending 67.42964339256287s
data key为：('2016-11-13', 39)
add label
make feature...
merge...
data shape：(27418, 224)
spending 65.50972557067871s
data key为：('2016-11-06', 39)
add label
make feature...
merge...
data shape：(27251, 224)
spending 63.628793716430664s
data key为：('2016-10-30', 39)
add label
make feature...
merge...
data shape：(27116, 224)
spending 61.69500517845154s
data key为：('2016-10-23', 39)
add label
make feature...
merge...
data shape：(27085, 224)
spending 59.591632604599s
data key为：('2016-10-16', 39)
add label
make feature...
merge...
data shape：(27093, 224)
spending 57.80337977409363s
data key为：('2016-10-09', 39)
add label
make feature...
merge...
data shape：(26987, 224)
spending 55.99549126625061s
data key为：('2016-10-02', 39)
add label
make feature...
merge...
data shape：(26949, 224)
spending 54.1381938457489s
data key为：('2016-09-25', 39)
add label
make feature...
merge...
data shape：(27032, 224)
spending 52.23228430747986s
data key为：('2016-09-18', 39)
add label
make feature...
merge...
data shape：(26776, 222)
spending 50.634512186050415s

C:\Users\Alex\Anaconda3\envs\python36\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  This is separate from the ipykernel package so we can avoid doing imports until

data key为：('2016-09-11', 39)
add label
make feature...
merge...
data shape：(26767, 224)
spending 48.63194274902344s
data key为：('2016-09-04', 39)
add label
make feature...
merge...
data shape：(26707, 224)
spending 47.33936953544617s
data key为：('2016-08-28', 39)
add label
make feature...
merge...
data shape：(26806, 224)
spending 44.81316518783569s
data key为：('2016-08-21', 39)
add label
make feature...
merge...
data shape：(26698, 224)
spending 43.06376814842224s
data key为：('2016-08-14', 39)
add label
make feature...
merge...
data shape：(26261, 224)
spending 42.38667440414429s
data key为：('2016-08-07', 39)
add label
make feature...
merge...
data shape：(26168, 224)
spending 39.38863754272461s
data key为：('2016-07-31', 39)
add label
make feature...
merge...
data shape：(26106, 222)
spending 37.70717144012451s
data key为：('2016-07-24', 39)
add label
make feature...
merge...
data shape：(26147, 224)
spending 35.598775148391724s
data key为：('2016-07-17', 39)
add label
make feature...
merge...
data shape：(26049, 224)
spending 33.496402978897095s
data key为：('2016-07-10', 39)
add label
make feature...
merge...
data shape：(26162, 224)
spending 31.890783548355103s
data key为：('2016-07-03', 39)
add label
make feature...
merge...
data shape：(26806, 224)
spending 28.873795747756958s
data key为：('2016-06-26', 39)
add label
make feature...
merge...
data shape：(24771, 224)
spending 26.687645435333252s
data key为：('2016-06-19', 39)
add label
make feature...
merge...
data shape：(21834, 224)
spending 26.83740735054016s
data key为：('2016-06-12', 39)
add label
make feature...
merge...
data shape：(18893, 224)
spending 25.707265853881836s
data key为：('2016-06-05', 39)
add label
make feature...
merge...
data shape：(16061, 224)
spending 23.10143280029297s
data key为：('2016-05-29', 39)
add label
make feature...
merge...
data shape：(13094, 224)
spending 21.72488570213318s
data key为：('2016-05-22', 39)
add label
make feature...
merge...
data shape：(10600, 224)
spending 20.65079951286316s
data key为：('2016-05-15', 39)
add label
make feature...
merge...
data shape：(10548, 224)
spending 19.900768041610718s
data key为：('2016-05-08', 39)
add label
make feature...
merge...
data shape：(10499, 224)
spending 19.24164628982544s
data key为：('2016-05-01', 39)
add label
make feature...
merge...
data shape：(10338, 224)
spending 18.490501403808594s
data key为：('2016-04-24', 39)
add label
make feature...
merge...
data shape：(10330, 224)
spending 17.71265149116516s
data key为：('2016-04-17', 39)
add label
make feature...
merge...
data shape：(10300, 224)
spending 17.190137147903442s
data key为：('2016-04-10', 39)
add label
make feature...
merge...
data shape：(10282, 224)
spending 16.42303490638733s
data key为：('2016-04-03', 39)
add label
make feature...
merge...
data shape：(10258, 224)
spending 15.843756437301636s
data key为：('2016-03-27', 39)
add label
make feature...
merge...
data shape：(10346, 224)
spending 15.100665092468262s
data key为：('2016-03-20', 39)
add label
make feature...
merge...
data shape：(10382, 224)
spending 14.48727822303772s
data key为：('2016-03-13', 39)
add label
make feature...
merge...
data shape：(10342, 224)
spending 13.786143064498901s
data key为：('2016-03-06', 39)
add label
make feature...
merge...
data shape：(10314, 224)
spending 13.196722745895386s
data key为：('2016-02-28', 39)
add label
make feature...
merge...
data shape：(10318, 224)
spending 12.256216287612915s
data key为：('2016-02-21', 39)
add label
make feature...
merge...
data shape：(10302, 224)
spending 11.693750143051147s
data key为：('2016-02-14', 39)
add label
make feature...
merge...
data shape：(10242, 224)
spending 11.225006341934204s
data key为：('2016-02-07', 39)
add label
make feature...
merge...
data shape：(10243, 224)
spending 10.439107179641724s
data key为：('2017-03-19', 35)
add label
make feature...
merge...
data shape：(24969, 224)
spending 97.86831974983215s

C:\Users\Alex\Anaconda3\envs\python36\lib\site-packages\ipykernel_launcher.py:8: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

data key为：('2017-03-26', 28)
add label
make feature...
merge...
data shape：(20049, 224)
spending 100.70766830444336s
data key为：('2017-04-02', 21)
add label
make feature...
merge...
data shape：(14999, 224)
spending 100.98183488845825s
data key为：('2017-04-09', 14)
add label
make feature...
merge...
data shape：(10008, 224)
spending 102.9341950416565s
data key为：('2017-04-16', 7)
add label
make feature...
merge...
data shape：(5012, 224)
spending 102.6565203666687s
data key为：('2017-04-23', 39)
add label
make feature...
merge...
data shape：(32019, 224)
spending 108.79204368591309s

In [48]:
predictors = [f for f in test_feat.columns if f not in (['id','store_id','visit_date','end_date','air_area_name','visitors','month'])]

params = {
    'learning_rate': 0.02,
    'boosting_type': 'gbdt',
    'objective': 'regression',
    'metric': 'rmse',
    'sub_feature': 0.7,
    'num_leaves': 60,
    'min_data': 100,
    'min_hessian': 1,
    'verbose': -1,
}

t0 = time.time()
lgb_train = lgb.Dataset(train_feat[predictors], train_feat['visitors'])
lgb_test = lgb.Dataset(test_feat[predictors], test_feat['visitors'])

gbm = lgb.train(params,lgb_train,2300)
pred = gbm.predict(test_feat[predictors])

print('训练用时{}秒'.format(time.time() - t0))

训练用时484.4806363582611秒

In [49]:
subm = pd.DataFrame({'id':test_feat.store_id + '_' + test_feat.visit_date,'visitors':np.expm1(pred)})
subm = submission[['id']].merge(subm,on='id',how='left').fillna(0)
subm.to_csv(r'..\sub{}.csv'.format(datetime.datetime.now().strftime('%Y%m%d_%H%M%S')),
                  index=False,  float_format='%.4f')

In [54]:
pd.Series(gbm.feature_importance(importance_type='gain'),
          index=gbm.feature_name()).sort_values(ascending=False).head(100)

store_dow_exp_mean1000_0.985         4.754856e+06
store_dow_exp_mean1000_0.99          3.471490e+06
store_dow_exp_mean1000_0.98          1.010644e+06
store_holiday2_mean1000              4.584368e+05
store_dow_exp_mean1000_0.999         4.003780e+05
store_count56                        3.980136e+05
store_holiday2_median1000            2.715023e+05
store_dow_exp_mean1000_0.97          1.727755e+05
store_mean14                         1.394683e+05
store_dow_median56                   1.382443e+05
4store_dow_count1000                 1.207750e+05
air_reserve_visitors                 9.906990e+04
longitude                            6.856603e+04
store_holiday_count1000              6.201959e+04
ahead_holiday2_-1                    6.198276e+04
latitude                             6.118288e+04
store_mean_56_1000_rate              6.110970e+04
ahead_holiday_-1                     5.672220e+04
store_mean28                         4.521081e+04
store_count28                        4.489344e+04
store_count14                        4.407628e+04
4store_dow_mean1000                  4.224938e+04
4dow                                 4.162526e+04
hpg_date_visitors                    4.092720e+04
store_exp_weight_sum1000             3.942168e+04
store_median14                       3.930156e+04
store_dow_median1000                 3.874847e+04
store_holiday2_std1000               3.632161e+04
store_holiday2_max1000               3.329017e+04
store_diff_std                       3.287427e+04
                                         ...
store_max1000                        1.617593e+04
1store_dow_sum1000                   1.594159e+04
store_holiday_mean1000               1.582493e+04
genre_max1000                        1.581920e+04
1store_dow_mean1000                  1.575318e+04
ahead_holiday2_1                     1.565944e+04
store_skew1000                       1.547758e+04
genre_dow_median1000                 1.522614e+04
air_diff_time_mean                   1.506383e+04
sgenre_mean_56_1000_rate             1.478508e+04
diff_of_day                          1.449440e+04
store_dow_exp_weight_sum1000_0.97    1.449181e+04
6store_dow_median1000                1.446414e+04
0store_dow_mean1000                  1.438094e+04
genre_skew56                         1.427402e+04
store_dow_max1000                    1.394345e+04
genre_max56                          1.379241e+04
air_area_name0                       1.371849e+04
store_holiday_skew1000               1.366299e+04
genre_dow_skew1000                   1.365067e+04
3store_dow_mean1000                  1.357002e+04
store_dow_skew1000                   1.342597e+04
store_holiday_min1000                1.305352e+04
genre_mean_28_56_rate                1.304679e+04
hpg_diff_time_mean                   1.285886e+04
store_dow_max28                      1.249201e+04
store_dow_max56                      1.239070e+04
1store_dow_median1000                1.231674e+04
genre_dow_count1000                  1.229630e+04
store_std56                          1.218936e+04
Length: 100, dtype: float64